application:
  host: 0.0.0.0
  port: 8000
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5431
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 2000
